version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports: 
      - "3000:3000"
    depends_on:
      - mongo
  
  mongo:
    container_name: mongo
    image: mongo
    volumes: 
      - ../mongo/data:/data/db
    ports:
      - "8080:27017"